#!/usr/bin/env node
/**
 * DEVOS Setup CLI
 * Run: npx devos-setup
 * 
 * Interactively configures a DEVOS profile in the current directory.
 * Detects GitHub username from git remote, pre-fills sensible defaults,
 * writes config.yml and patches README.md in one pass.
 */

const readline = require("readline");
const fs = require("fs");
const path = require("path");
const { execSync } = require("child_process");

const GREEN  = "\x1b[32m";
const BLUE   = "\x1b[34m";
const YELLOW = "\x1b[33m";
const CYAN   = "\x1b[36m";
const RESET  = "\x1b[0m";
const BOLD   = "\x1b[1m";
const DIM    = "\x1b[2m";

const rl = readline.createInterface({ input: process.stdin, output: process.stdout });
const ask = (q) => new Promise((res) => rl.question(q, res));

function detect_github_username() {
  try {
    const remote = execSync("git remote get-url origin 2>/dev/null", { encoding: "utf8" }).trim();
    const match = remote.match(/github\.com[:/]([^/]+)\//);
    return match ? match[1] : null;
  } catch { return null; }
}

function detect_repo_name() {
  try {
    const remote = execSync("git remote get-url origin 2>/dev/null", { encoding: "utf8" }).trim();
    const match = remote.match(/github\.com[:/][^/]+\/([^/.]+)/);
    return match ? match[1] : null;
  } catch { return null; }
}

async function main() {
  console.clear();
  console.log(`
${GREEN}${BOLD}╔══════════════════════════════════════════════════════════════╗
║  DEVOS v2  ·  Developer Operating System  ·  Setup Wizard    ║
╚══════════════════════════════════════════════════════════════╝${RESET}
${DIM}This wizard configures your DEVOS profile in ~60 seconds.
It writes config.yml and patches README.md with your info.${RESET}
`);

  const detected_user = detect_github_username();
  const detected_repo = detect_repo_name();

  if (detected_repo && detected_repo !== detected_user) {
    console.log(`${YELLOW}⚠  Your repo is named "${detected_repo}" but it should be named`);
    console.log(`   "${detected_user || 'YOUR_USERNAME'}" for a GitHub profile README.`);
    console.log(`   Rename it in: github.com/${detected_user || '?'}/${detected_repo}/settings${RESET}\n`);
  }

  console.log(`${CYAN}── IDENTITY ─────────────────────────────────────────────────${RESET}`);
  const username    = await ask(`GitHub username ${detected_user ? `[${detected_user}]` : ""}: `) || detected_user || "";
  const displayName = await ask(`Your display name: `);
  const tagline     = await ask(`Your tagline/motto [Ship it. Learn from it. Ship it better.]: `) 
                        || "Ship it. Learn from it. Ship it better.";

  console.log(`\n${CYAN}── CURRENT STATUS ───────────────────────────────────────────${RESET}`);
  const mission     = await ask(`What are you building right now? `);
  const learning    = await ask(`What are you currently learning? `);
  const strength    = await ask(`Signal strength 0-100 (how active/available are you) [80]: `) || "80";

  console.log(`\n${CYAN}── PROJECTS (enter up to 3, press Enter to skip) ────────────${RESET}`);
  const projects = [];
  for (let i = 1; i <= 3; i++) {
    const name = await ask(`Project ${i} name (or Enter to skip): `);
    if (!name) break;
    const url  = await ask(`  GitHub URL: `);
    const pct  = await ask(`  Progress % [50]: `) || "50";
    const type = await ask(`  Type (OSS/Side/Study/PR) [Side]: `) || "Side";
    projects.push({ name, url, progress: parseInt(pct), type, status: "IN DEV", description: "" });
  }

  console.log(`\n${CYAN}── CONNECT ──────────────────────────────────────────────────${RESET}`);
  const linkedin  = await ask(`LinkedIn handle (without linkedin.com/in/): `);
  const twitter   = await ask(`Twitter/X handle (without @): `);
  const website   = await ask(`Website URL: `);
  const email     = await ask(`Email address: `);

  console.log(`\n${CYAN}── SKILL ICONS (skillicons.dev names, comma-separated) ──────${RESET}`);
  const core_icons = await ask(`Core languages [typescript,python,javascript,go]: `) 
                       || "typescript,python,javascript,go";
  const fw_icons   = await ask(`Frameworks [react,nextjs,nodejs,fastapi]: `) 
                       || "react,nextjs,nodejs,fastapi";
  const infra_icons = await ask(`Infrastructure [docker,kubernetes,git,linux]: `) 
                       || "docker,kubernetes,git,linux";

  rl.close();

  // ── WRITE CONFIG.YML ──────────────────────────────────────────────────────
  const config = `# DEVOS v2 · config.yml
# Generated by npx devos-setup · Edit anytime

identity:
  github_username: "${username}"
  display_name: "${displayName}"
  tagline: "${tagline}"

status:
  current_mission: "${mission || 'Building something that matters'}"
  learning: "${learning || 'Exploring new technologies'}"
  open_to:
    - "collaborations"
    - "code reviews"
    - "mentoring"
  signal_strength: ${parseInt(strength) || 80}

projects:
${projects.map(p => `  - name: "${p.name}"
    url: "${p.url}"
    status: "${p.status}"
    progress: ${p.progress}
    type: "${p.type}"
    description: ""`).join("\n") || `  - name: "Add your projects"
    url: "https://github.com/${username}/my-project"
    status: "IN DEV"
    progress: 50
    type: "Side"
    description: ""`}

skills:
  - name: "TypeScript"
    level: "Senior"
  - name: "Python"
    level: "Senior"
  - name: "Add more in config.yml"
    level: "Learning"

skill_icons:
  core: "${core_icons}"
  frameworks: "${fw_icons}"
  infrastructure: "${infra_icons}"
  toolchain: "git,linux,vim,vscode"

connect:
  linkedin: "${linkedin}"
  twitter: "${twitter}"
  website: "${website || 'https://github.com/' + username}"
  email: "${email}"

integrations:
  wakatime: false
  blog_rss: false
`;

  fs.writeFileSync("config.yml", config);
  console.log(`\n${GREEN}✓ config.yml written${RESET}`);

  // ── PATCH README.MD ────────────────────────────────────────────────────────
  if (fs.existsSync("README.md")) {
    let readme = fs.readFileSync("README.md", "utf8");
    readme = readme.split("YOUR_USERNAME").join(username);
    readme = readme.split("YOUR_LINKEDIN").join(linkedin || "your-linkedin");
    readme = readme.split("YOUR_TWITTER").join(twitter || "your-twitter");
    readme = readme.split("YOUR_WEBSITE").join(website || `https://github.com/${username}`);
    readme = readme.split("YOUR_EMAIL").join(email || `contact@${username}`);
    fs.writeFileSync("README.md", readme);
    console.log(`${GREEN}✓ README.md patched with your info${RESET}`);
  }

  // ── NEXT STEPS ─────────────────────────────────────────────────────────────
  console.log(`
${GREEN}${BOLD}══════════════════════════════════════════════════════════════
  DEVOS v2 configured. 3 steps left:
══════════════════════════════════════════════════════════════${RESET}

${BOLD}1. Enable GitHub Actions permissions${RESET}
   → Your repo Settings → Actions → General
   → Set "Workflow permissions" to "Read and write permissions"
   → Save

${BOLD}2. Run the first update manually${RESET}
   → Actions tab → "DEVOS — Auto Update README" → Run workflow
   → This populates your DEVOS Score and Code DNA for the first time

${BOLD}3. (Optional) Add AI Terminal support${RESET}
   → Get a free Anthropic API key at console.anthropic.com
   → Repo Settings → Secrets → New secret
   → Name: ANTHROPIC_API_KEY   Value: your-key
   → Now visitors can !ask questions and get replies in your voice

${DIM}Full guide: SETUP.md
Score methodology: SCORE_METHODOLOGY.md${RESET}

${GREEN}${BOLD}Ready. Commit and push — your DEVOS profile is live. ✓${RESET}
`);
}

main().catch(console.error);
